// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/views/Admin.vue')['default']
    CrontabManager: typeof import('./src/views/admin/crontabManager.vue')['default']
    DailLog: typeof import('./src/components/common/DailLog.vue')['default']
    DashBoard: typeof import('./src/views/admin/DashBoard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    GeneralInformation: typeof import('./src/components/admin/systemstatus/generalInformation.vue')['default']
    Index: typeof import('./src/views/Index.vue')['default']
    IoStatus: typeof import('./src/components/admin/systemstatus/ioStatus.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    LogManager: typeof import('./src/views/admin/LogManager.vue')['default']
    Nav: typeof import('./src/components/admin/Nav.vue')['default']
    SystemSetting: typeof import('./src/views/admin/SystemSetting.vue')['default']
    SystemStatus: typeof import('./src/views/admin/SystemStatus.vue')['default']
    TopLeftMemory: typeof import('./src/components/admin/dashboard/topLeftMemory.vue')['default']
    UsageStatus: typeof import('./src/components/admin/systemstatus/usageStatus.vue')['default']
    UserList: typeof import('./src/components/admin/usermanager/UserList.vue')['default']
    UserManager: typeof import('./src/views/admin/UserManager.vue')['default']
  }
}

export { }
