// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/views/Admin.vue')['default']
    DailLog: typeof import('./src/components/common/DailLog.vue')['default']
    DashBoard: typeof import('./src/views/admin/DashBoard.vue')['default']
    DemoCharts1: typeof import('./src/components/DemoCharts1.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HistoricalAlarm: typeof import('./src/components/admin/dashboard/HistoricalAlarm.vue')['default']
    Index: typeof import('./src/views/Index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Login: typeof import('./src/views/Login.vue')['default']
    LogManager: typeof import('./src/views/admin/LogManager.vue')['default']
    MonitoringTaskList: typeof import('./src/components/admin/dashboard/monitoringTaskList.vue')['default']
    Nav: typeof import('./src/components/admin/Nav.vue')['default']
    SystemSetting: typeof import('./src/views/admin/SystemSetting.vue')['default']
    SystemStatus: typeof import('./src/views/admin/SystemStatus.vue')['default']
    UserList: typeof import('./src/components/admin/usermanager/UserList.vue')['default']
    UserManager: typeof import('./src/views/admin/UserManager.vue')['default']
    VulnInfo: typeof import('./src/components/admin/dashboard/VulnInfo.vue')['default']
  }
}

export { }
